<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>10010-icon-service-Quickstart-Center.ico</ApplicationIcon>
    <Copyright></Copyright>
    <PackageIcon></PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="10010-icon-service-Quickstart-Center.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
  </ItemGroup>

</Project>
